config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  resources :likes
  root 'top#main'
  post 'top/login' => "top#login"
  get 'top/logout'
  get 'top/main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user, optional: true
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, uniqueness: true
    
    has_many :tweets
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        user = User.find_by(uid: session[:login_uid])
        user.like_tweets << tweet
        redirect_to root_path
    end
    def destroy
        tweet = Tweet.find(params[:id])
        user = User.find_by(uid: session[:login_uid])
        tweet.likes.find_by(user_id: user.id).destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    @tweet = Tweet.all
  end
    
  def login
    @tweet = Tweet.all
    user = User.find_by(uid: params[:uid])
    if user and BCrypt::Password.new(user.pass) == params[:pass]
       session[:login_uid] = params[:uid]
       render 'top/main'
    else
      render 'login'
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
     @tweet = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(message: params[:tweet][:message], user_id: session[:login_uid])
    if @tweet.save
      flash[:notice] = '1レコード追加しました'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.destroy
      flash[:notice] = '1レコード削除しました'
    end
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(uid: params[:user][:uid], pass: BCrypt::Password.create(params[:user][:pass]), profile: params[:user][:profile])
    if @user.save
      flash[:notice] = 'userを追加しました'
      redirect_to users_path
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(profile: params[:user][:profile])
      flash[:notice] = 'userを更新しました'
      redirect_to users_path
    else
      render 'edit'
    end
  end
  

  def destroy
    user = User.find(params[:id])
    if user.destroy
     flash[:notice] = 'userを削除しました'
    end
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if !session[:login_uid] %>
      <br><strong>ログインしていません</strong>
    <% else %>
      <br><strong><%= session[:login_uid] %>さんでログインしています</strong>
    <% end %>
  </body>
</html>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %><br>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %><br>
    <%= submit_tag 'ログイン' %>
<% end %>
<br><%= link_to "ユーザー一覧", '/users' %>

app/views/top/main.html.erb
<% if !session[:login_uid] %>
    <%= link_to "ログイン", '/top/login', method: :post %><br>
<% end %>
<% @tweet.each do |e| %>
    <p> 
        <%= e.message %><br>
        <% if session[:login_uid] %>
            <%= link_to 'いいね', likes_path(tweet_id: e.id), method: :post %>
            <%= link_to 'いいね削除', like_path(e), method: :delete %>
            <% if e.likes.count == 0 %>
                <%= link_to  likes_path(tweet_id: e.id), method: :post  do %>
                    <i class="far fa-heart"></i>
                <% end %>
            <% else %>
                <%= link_to  like_path(e), method: :delete do %>
                    <i class="fas fa-heart"></i>
                <% end %>
            <% end %>
            <%= link_to '削除', "/tweets/#{e.id}", method: :delete %>
        <% end %>
    </p> 
<% end %>
<%= link_to "ユーザー一覧", '/users' %><br>
<% if session[:login_uid] %>
    <%= link_to "ツイートする", '/tweets/new' %>
    <%= link_to 'ログアウト', top_logout_path %>
<% end %>

app/views/tweets/index.html.erb
<% @tweet.each do |e| %>
    <p> 
        <%= e.message %><br>
        <%= link_to 'いいね', likes_path(tweet_id: e.id), method: :post %>
        <%= link_to 'いいね削除', like_path(e), method: :delete %>
        <%= link_to '削除', "/tweets/#{e.id}", method: :delete %> 
    </p> 
<% end %>
 <%= link_to "登録する", '/tweets/new' %>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
    <span style="color:red;">
        <h3>エラーがあります。</h3>
        <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </span>
<% end %>

<%= form_for @tweet, url: {action: :create} do |f| %>
    <p><%= f.label :message, 'ツイート文' %>
    <%= f.text_field :message %></p>
    <%= f.submit 'ツイート' %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.present? %>
    <span style="color:red;">
        <h3>エラーがあります。</h3>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </span>
<% end %>

<%= form_for @user, url: {action: :update} do |f| %>
    <p><%= @user.uid %></p>
    <p><%= @user.pass %></p>
    <p><%= f.label :profile, 'プロフィール' %>
    <%= f.text_field :profile %></p>
    <%= f.submit '更新' %>
<% end %>

app/views/users/index.html.erb
<% @user.each do |e| %>
    <p> 
        ユーザー名：<%= e.uid %><br>
        パスワード：<%= e.pass %><br>
        プロフィール：<%= e.profile %><br>
        <% if e.uid == session[:login_uid] %>
            <%= link_to '編集', "/users/#{e.id}/edit" %>
        <% end %>
        <%= link_to '削除', "/users/#{e.id}", method: :delete %> 
    </p> 
<% end %>
<%= link_to "登録する", '/users/new' %><br>
<%= link_to "メイン", '/top/main' %>

app/views/users/new.html.erb
<% if @user.errors.present? %>
    <span style="color:red;">
        <h3>エラーがあります。</h3>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </span>
<% end %>

<%= form_for @user, url: {action: :create} do |f| %>
    <p><%= f.label :uid, 'ユーザー名' %>
    <%= f.text_field :uid %></p>
    <p><%= f.label :pass, 'パスワード' %>
    <%= f.text_field :pass %></p>
    <%= f.submit '登録' %>
<% end %>

app/views/users/show.html.erb
ユーザー名：<%= @user.uid %><br>
パスワード：<%= @user.pass %><br>
プロフィール：<%= @user.profile %><br>
<%= link_to "メイン", '/' %>